"""Create Task model

Revision ID: 204142b9f59a
Revises: 
Create Date: 2024-05-27 08:57:47.698763

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '204142b9f59a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.Enum('execute_code', name='tasktypeenum'), nullable=True),
    sa.Column('task_status', sa.Enum('pending', 'completed', 'failed', name='taskstatusenum'), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cpu', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gpu', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ram', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('output', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###