"""Add Task model

Revision ID: 23c6bbcb582e
Revises: 
Create Date: 2024-05-27 16:10:46.659885

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '23c6bbcb582e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('task_type', sa.Enum('execute_code', name='tasktypeenum'), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_status', sa.Enum('pending', 'completed', 'failed', name='taskstatusenum'), nullable=True),
    sa.Column('cpu', sa.Integer(), nullable=False),
    sa.Column('gpu', sa.Integer(), nullable=False),
    sa.Column('ram', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('output', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('container_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('elapsed_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###